global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (IP fixo da VM, como definido no hosts.ini)
  - job_name: 'dockerhost-node'
    static_configs:
      - targets: ['10.10.30.10:9100']

  # cAdvisor
  - job_name: 'dockerhost-cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Raspberry Pi (Edge Node)
  - job_name: 'rpi-edge'
    static_configs:
      - targets: ['192.168.0.5:9100']

  # Traefik Metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['10.10.30.10:8082']

  # CrowdSec Metrics
  - job_name: 'crowdsec'
    static_configs:
      - targets: ['10.10.30.10:6060']
        labels:
          machine: 'dockerhost'
