global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (IP fixo da VM, como definido no hosts.ini)
  - job_name: 'dockerhost-node'
    static_configs:
      - targets: ['10.10.30.10:9100']

  # --- Proxmox (Host FÃ­sico) ---
  - job_name: 'proxmox-host'
    static_configs:
      - targets: ['192.168.0.200:9100']

  # --- Vault (VM Vault) ---
  - job_name: 'vault-node'
    static_configs:
      - targets: ['10.10.40.10:9100']

  # cAdvisor
  - job_name: 'dockerhost-cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Raspberry Pi (Edge Node)
  - job_name: 'rpi-edge'
    static_configs:
      - targets: ['192.168.0.5:9100']

  # Traefik Metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['10.10.30.10:8082']

  # CrowdSec Metrics
  - job_name: 'crowdsec'
    static_configs:
      - targets: ['10.10.30.10:6060']
        labels:
          machine: 'dockerhost'

  # --- Proxmox VE (LXC/VMs) ---
  - job_name: 'proxmox-ve'
    metrics_path: /pve
    params:
      module: [default]
    static_configs:
      - targets:
        - 192.168.0.200  # IP do Proxmox
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221  # Nome do container + Porta interna

  - job_name: 'tailscale-vpn'
    static_configs:
      - targets: ['10.10.30.10:9002']
    metrics_path: /metrics
