services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/authentik
      - GID=1000
    volumes:
      - crowdsec_db:/var/lib/crowdsec/data
      - crowdsec_config:/etc/crowdsec
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec/notifications.yaml:/etc/crowdsec/notifications.yaml
      # Leitura de Logs (Mesma t√©cnica do Alloy)
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true

volumes:
  crowdsec_db:
  crowdsec_config:
