# Nostr-rs-relay Configuration
# Docs: https://github.com/scsibug/nostr-rs-relay

[info]
relay_url = "wss://nostr.home"
name = "Fajre Sovereign Relay"
description = "Relay Pessoal Privado (Tor + Whitelist)"
pubkey = "692db6f2450642ead458703b77b9864ac4c6bf30c246000cd2bf5cd3e0fb1750" 
contact = "meu-alias@email.com"

[database]
engine = "sqlite"
data_directory = "/var/lib/nostr-rs-relay"

[network]
port = 8080
address = "0.0.0.0"

[options]
reject_future_seconds = 1800 # 30 min no futuro max

[authorization]
# Whitelist Nativa
# Ninguém posta aqui, só eu.
pubkey_whitelist = [
  "692db6f2450642ead458703b77b9864ac4c6bf30c246000cd2bf5cd3e0fb1750"
]
