http:
  routers:
    # Router para API (Rob√¥s/CLI/Apps)
    vault-api:
      rule: "Host(`vault.home`) && PathPrefix(`/v1`)"
      service: "vault-service"
      entryPoints:
        - "websecure"
      tls: {}
      priority: 100
      # SEM MIDDLEWARE AUTHENTIK AQUI (O Vault se protege sozinho)

    # Router para UI (Humanos/Navegador)
    vault-ui:
      rule: "Host(`vault.home`)"
      service: "vault-service"
      entryPoints:
        - "websecure"
      tls: {}
      middlewares:
        - "authentik@docker"

  services:
    vault-service:
      loadBalancer:
        servers:
          - url: "http://10.10.40.10:8200"
