route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ntfy'

receivers:
  - name: 'ntfy'
    webhook_configs:
      - url: 'http://ntfy:80/seu_topico_secreto'
        # Quando eu criar o usu√°rio no ntfy, descomentar abaixo:
        # http_config:
        #   authorization:
        #     credentials: "tk_seu_token_aqui"
